[package]
name = "wibrary"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "wbin"
path = "src/main.rs"

[dependencies]

[build-dependencies]
cbindgen = "0.20.0"